apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
spec:
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      labels:
        app: search-svc
    spec:
      containers:
      - name: search-svc
        image: ajav00/search-svc
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: search-svc-config
        ports:
        - containerPort: 80
          name: web
        - containerPort: 7777
          name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  type: ClusterIP
  selector:
    app: search-svc
  ports:
  - name: web
    port: 80
    targetPort: 80
